name: build-cmd
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cmd: [ddnsclient, cname, cfipchange]
    steps:

    - name: Set up Go 1.17
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        ref: master
        
    - name: Build
      run: |
        cd cmd/${{ matrix.cmd }}
        env CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ../../linux-amd64/${{ matrix.cmd }} -ldflags="-s -w" .
        env CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=7 go build -o ../../linux-arm-7/${{ matrix.cmd }} -ldflags="-s -w" .
        env CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o ../../darwin-amd64/${{ matrix.cmd }} -ldflags="-s -w" .
        env CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -o ../../darwin-arm64/${{ matrix.cmd }} -ldflags="-s -w" .
        env CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o ../../windows-amd64/${{ matrix.cmd }}.exe -ldflags="-s -w" .
        env CGO_ENABLED=0 GOOS=freebsd GOARCH=amd64 go build -o ../../freebsd-amd64/${{ matrix.cmd }} -ldflags="-s -w" .
        env CGO_ENABLED=0 GOOS=openbsd GOARCH=amd64 go build -o ../../openbsd-amd64/${{ matrix.cmd }} -ldflags="-s -w" .
        env CGO_ENABLED=0 GOOS=netbsd GOARCH=amd64 go build -o ../../netbsd-amd64/${{ matrix.cmd }} -ldflags="-s -w" .
        env CGO_ENABLED=0 GOOS=dragonfly GOARCH=amd64 go build -o ../../dragonfly-amd64/${{ matrix.cmd }} -ldflags="-s -w" .
        cd ../..
        env GOPATH=$PWD/gopath go get -u github.com/missdeer/cicdutil
      
    - name: Upload artifact ${{ matrix.cmd }}-linux-amd64
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: ${{ matrix.cmd }}-linux-amd64
        # Directory containing files to upload
        path: linux-amd64

    - name: Upload artifact ${{ matrix.cmd }}-linux-arm-7
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: ${{ matrix.cmd }}-linux-arm-7
        # Directory containing files to upload
        path: linux-arm-7

    - name: Upload artifact ${{ matrix.cmd }}-darwin-amd64
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: ${{ matrix.cmd }}-darwin-amd64
        # Directory containing files to upload
        path: darwin-amd64

    - name: Upload artifact ${{ matrix.cmd }}-darwin-arm64
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: ${{ matrix.cmd }}-darwin-arm64
        # Directory containing files to upload
        path: darwin-arm64
        
    - name: Upload artifact ${{ matrix.cmd }}-dragonfly-amd64
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: ${{ matrix.cmd }}-dragonfly-amd64
        # Directory containing files to upload
        path: dragonfly-amd64

    - name: Upload artifact ${{ matrix.cmd }}-openbsd-amd64
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: ${{ matrix.cmd }}-openbsd-amd64
        # Directory containing files to upload
        path: openbsd-amd64

    - name: Upload artifact ${{ matrix.cmd }}-netbsd-amd64
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: ${{ matrix.cmd }}-netbsd-amd64
        # Directory containing files to upload
        path: netbsd-amd64

    - name: Upload artifact ${{ matrix.cmd }}-freebsd-amd64
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: ${{ matrix.cmd }}-freebsd-amd64
        # Directory containing files to upload
        path: freebsd-amd64

    - name: Upload artifact ${{ matrix.cmd }}-windows-amd64
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: ${{ matrix.cmd }}-windows-amd64
        # Directory containing files to upload
        path: windows-amd64

    - name: Remove old artifacts
      run: |
        gopath/bin/cicdutil -p github -u missdeer -t ${{ secrets.GH_TOKEN }} -r ${{ matrix.cmd }} -k 0 -a delete
